# Book settings
title: Urban Grammar Data Processing
author: Dani Arribas-Bel, Martin Fleischmann
logo: logo.jpeg

execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/urbangrammarai/data_processing
launch_buttons:
  binderhub_url: https://mybinder.org
